version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    hostname: postgres
    container_name: reesle-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - apps/api/.database.env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: reesle-adminer
    restart: always
    ports:
      - "80:8080"
    environment:
      ADMINER_DESIGN: "hydra"
    depends_on:
      - postgres

volumes:
  postgres:
    name: reesle-db
